### ISSUE TITLE
MAC版で使うと「PULL」実施しても反応がないです

### ISSUE THREAD

**Issue by gassyou** [Mikoshiba-Kyu/vscode-barretta#1]
Excel Version: MS Excel for Mac 16.64

ps version:
![image](https://user-images.githubusercontent.com/2518449/187843479-efcace4a-bd00-4e4a-8b07-a31615a98cd3.png)

現象：
「PULL」Commandを実施すると反応がないです

![image](https://user-images.githubusercontent.com/2518449/187841910-f7c8447c-c8e3-479f-a124-ef3c1ded62d8.png)

**Comment by Mikoshiba-Kyu** [comment]
Windowsでのみ動作します。
MacOSのサポートは現時点では予定していません。

**Comment by gassyou** [comment]
> Windowsでのみ動作します。 MacOSのサポートは現時点では予定していません。

了解しました。有難うございます。
